project:
  type: website

website:
  title: "Dr. Sebastian G. Mutz" # Î» - lynx
  reader-mode: true
  navbar:
    background: dark
    foreground: light
    search: true
    left:
      - text: "Research"
        menu:
          - research/research.qmd
          - research/publications.qmd
          - research/grants.qmd
      - text: "Courses"
        menu:
          - courses/glasgow.qmd
          - courses/tuebingen.qmd
          - courses/external.qmd
      - text: "Software"
        menu:
          - code/fsml.qmd
          - code/fplt.qmd
          - code/pyesd.qmd
      - text: "Service"
        menu:
          - service/outreach.qmd
          - service/service.qmd
      # - text: "Blog"
      #   href: blog/index.qmd
    right:
      - text: "CV"
        menu:
          - text: "View Online"
            href: cv/cv.qmd
          - text: "Download PDF"
            href: cv/cv.pdf
    tools:
      - icon: github
        href: https://github.com/sebastian-mutz/

format:
  html:
    theme: yeti # morph #sandstone
    highlight-style: nord #monokai
    css: styles.css
    toc: true

